
quotation_keys = ['instrument_id', 'name', 'now', 'low', 'high', 'open', 'close', 'volume', 'turnover',
                  'bid1', 'bid2', 'bid3', 'bid4', 'bid5',
                  'bid1_volume', 'bid2_volume', 'bid3_volume', 'bid4_volume', 'bid5_volume',
                  'ask1', 'ask2', 'ask3', 'ask4', 'ask5',
                  'ask1_volume', 'ask2_volume', 'ask3_volume', 'ask4_volume', 'ask5_volume', 'datetime']

sina_quotation_map = {
    'name': '股票名',
    'datetime': '时间（年月日 时分秒）',
    'now': '现价',
    'low': '今日最低价',
    'high': '今日最高价',
    # 'buy': '竞买价',
    # 'sell': '竞卖价',
    'open': '今开',
    'close': '昨收',
    'volume': '成交量',
    'turnover': '成交额',
    'bid1': '买1价',
    'bid2': '买2价',
    'bid3': '买3价',
    'bid4': '买4价',
    'bid5': '买5价',
    'bid1_volume': '买1量',
    'bid2_volume': '买2量',
    'bid3_volume': '买3量',
    'bid4_volume': '买4量',
    'bid5_volume': '买5量',
    'ask1': '卖1价',
    'ask2': '卖2价',
    'ask3': '卖3价',
    'ask4': '卖4价',
    'ask5': '卖5价',
    'ask1_volume': '卖1量',
    'ask2_volume': '卖2量',
    'ask3_volume': '卖3量',
    'ask4_volume': '卖4量',
    'ask5_volume': '卖5量',
}

tencent_quotation_map = {
    'name': '股票名',
    # 'code': '',
    'now': '现价',
    'open': '今开',
    'close': '昨收',
    'turnover': '成交额',
    'datetime': '时间',
    'volume': '成交量',
    # 'PE': '',
    # 'PB': '',
    'bid1': '买1价',
    'bid2': '买2价',
    'bid3': '买3价',
    'bid4': '买4价',
    'bid5': '买5价',
    'ask1': '卖1价',
    'ask2': '卖2价',
    'ask3': '卖3价',
    'ask4': '卖4价',
    'ask5': '卖5价',
    'high': '今日最高价',
    # 'high_2': '',
    'low': '今日最低价',
    # 'low_2': '',
    # 'bid_volume': '',
    'bid1_volume': '买1量',
    'bid2_volume': '买2量',
    'bid3_volume': '买3量',
    'bid4_volume': '买4量',
    'bid5_volume': '买5量',
    # 'ask_volume': '',
    'ask1_volume': '卖1量',
    'ask2_volume': '卖2量',
    'ask3_volume': '卖3量',
    'ask4_volume': '卖4量',
    'ask5_volume': '卖5量',
    # 'unknown': '',
    # '总市值': '',
    # '最近逐笔成交': '',
    # '涨停价': '',
    # '跌停价': '',
    # '成交量(手)': '',
    # '成交额(万)': '',
    # '涨跌': '',
    # '流通市值': '',
    # '振幅': '',
    # '涨跌(%)': '',
    # '价格/成交量(手)/成交额': ''
}
